# Check this file before committing a new version:
# http://lint.travis-ci.org/

language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"

notifications:
  email:
    on_success: change
    on_failure: change

# Install conda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose pandas statsmodels cython h5py
  - pip install -r pip-requirements.txt
  - python setup.py install

before_script:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  - cython --version

# run tests
script:
  - ./run-tests.py
